;;; early-init.el --- early configurations -*- lexical-binding: t; buffer-read-only: t; no-byte-compile: t -*-
;;;
;;; Commentary:
;;; Emacs confi by Andrey Orst.
;;; This file was automatically generated by `org-babel-tangle'.
;;; Do not change this file.  Main config is located in .config/emacs/README.org
;;;
;;; Code:

(defvar comp-deferred-compilation)
(setq comp-deferred-compilation t)

(custom-set-variables
 '(straight-repository-branch "develop")
 '(straight-check-for-modifications '(check-on-save find-when-checking))
 '(straight-vc-git-default-clone-depth 1)
 ;; '(straight-use-package-by-default t) 
)

(defvar bootstrap-version)
(defvar straight-repository-branch)
(setq straight-repository-branch "develop")
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)

;; (setq use-package-always-defer t
;;       ;; use-package-minimum-reported-time .001
;;       ;; use-package-verbose t
;;       ;; use-package-compute-statistics t
;; )

(use-package gcmh
  :straight t 
  :init
  (gcmh-mode 1))

(setq package-enable-at-startup nil)

(provide 'early-init)
;;; early-init.el ends here
